feat: add drag n drop functionality to section cards
open-craft/frontend-app-course-authoring pull request #17
Opened 2023-12-04 23:55 UTC by steff456

Resolves `private ref`: [BB-8219](https://tasks.opencraft.com/browse/BB-8219)

This PR,

-[x] Adds an endpoint for reordering the list of sections
-[x] Adds the functionality for drag and drop the sections cards
-[] Adds new tests for the functionality

**Demo**

https://github.com/open-craft/frontend-app-course-authoring/assets/20992645/1ce9a973-e950-439e-8966-3cadddbafd03

**Depends on**

- https://github.com/open-craft/frontend-app-course-authoring/pull/12

**Testing instructions**
- Follow instructions from the readme
- Checkout branch from https://github.com/openedx/edx-platform/pull/33667 and run `make cms-up` in devstack.
- Open any course outline by using this url format: http://localhost:2001/course/course-v1:edX+DemoX+Demo_Course/outline
- Drag and drop sections among them!

**Questions**

- I'm unsure if there's any preference on the style of the draggable objects, in the other front end they are using three dots so the users can understand they are able to drag and drop the cards.
- The same question goes for the `drag` animation, right now it is using the default

2023-12-05 06:27 UTC, navinkarkera commented
@steff456 Even though I like that the custom drag-n-drop implementation, we should probably use something like `react-DnD` as the current implementation is bit confusing as their is no indication about the drop position and implementing it by hand will require a lot more effort and time. See this [example](https://react-dnd.github.io/react-dnd/examples/sortable/simple), we want something similar. Also, after dropping an item it should not go back to its original position and wait for the API to complete, instead it should update the UI first and then update the backend via API and if for some reason the API call fails, we display an error message (which is already handled in exception handling).

> I'm unsure if there's any preference on the style of the draggable objects, in the other front end they are using three dots so the users can understand they are able to drag and drop the cards.

We don't need to add the three dots as per the new design. The curson already updates as expected so we don't need any changes in UI.

> The same question goes for the drag animation, right now it is using the default

We can keep the default animation for now from the [example](https://react-dnd.github.io/react-dnd/examples/sortable/simple)

2023-12-05 06:27 UTC, navinkarkera requested changes
@steff456 Even though I like that the custom drag-n-drop implementation, we should probably use something like `react-DnD` as the current implementation is bit confusing as their is no indication about the drop position and implementing it by hand will require a lot more effort and time. See this [example](https://react-dnd.github.io/react-dnd/examples/sortable/simple), we want something similar. Also, after dropping an item it should not go back to its original position and wait for the API to complete, instead it should update the UI first and then update the backend via API and if for some reason the API call fails, we display an error message (which is already handled in exception handling).

> I'm unsure if there's any preference on the style of the draggable objects, in the other front end they are using three dots so the users can understand they are able to drag and drop the cards.

We don't need to add the three dots as per the new design. The curson already updates as expected so we don't need any changes in UI.

> The same question goes for the drag animation, right now it is using the default

We can keep the default animation for now from the [example](https://react-dnd.github.io/react-dnd/examples/sortable/simple)

2023-12-05 14:54 UTC, steff456 commented
@navinkarkera I'll modify the implementation to use `react-dnd` and ping you once it is ready :)

2023-12-06 04:08 UTC, steff456 commented
@navinkarkera I just updated to use `dnd-react` library, I also updated the demo video in the description. With this changes now the UI updates first and then it sends the new order to the backend and now the animation is the same as the example you provided. 

Tomorrow I'll work on adding some tests and fixing the linting issues that appeared in the CI :)

2023-12-06 14:09 UTC, navinkarkera requested changes
@steff456 Thanks, I just pushed a commit to fix multiple requests on hover issue.

I see ~43 new commits as you seem to have use merge commit instead of rebasing with the base branch. Can you try to create a new branch from the base and cherry pick your and my last commit to cleanup the commit history?

2023-12-06 14:09 UTC, navinkarkera commented on src/course-outline/CourseOutline.jsx
> +      handleDragNDrop(idList);
This is sending multiple put requests on hover, instead we should only send a request on drop.

2023-12-08 07:51 UTC, navinkarkera requested changes
@steff456 Almost there. We have one more issue where if you try to select text via dragging the mouse in title while editing it, it drags the whole section. Maybe this issue can help fixing it: https://github.com/react-dnd/react-dnd/issues/335

2023-12-08 07:51 UTC, navinkarkera commented on src/course-outline/CourseOutline.jsx
> +  const initialSections = [...sectionsList];
@steff456 There was an issue with restoring section list back to original when the API fails as this line was `const initialSections = [...sections];` which is updated with sections so the restore did not work. I took the liberty to fix this and update sectionListOrder in reducer when the request is successful to handle failures in API after a successful attempt.

2023-12-08 16:50 UTC, steff456 commented on src/course-outline/CourseOutline.jsx
> +  const initialSections = [...sectionsList];
thanks for helping me with that!

2023-12-08 17:07 UTC, steff456 commented
@navinkarkera the last commit fixes the text editing issue. Please let me know if there's anything else this PR needs.

2023-12-11 05:39 UTC, navinkarkera requested changes
@steff456 The functionality now works as expected. We have an issue in firefox where the text inside the form cannot be selected. We can address this in a separate ticket as HTML5 drag n drop has some issues with firefox. For now it looks good.

We should add some tests (probably in `CourseOutline.test.jsx`) to test ordering when it runs successfully as well as when something goes wrong (restoreCallback).

2023-12-11 05:39 UTC, navinkarkera commented on src/course-outline/section-card/SectionCard.jsx
> +        className="nodrag"
@steff456 It seems to have no effect, we can remove this.

2023-12-11 16:53 UTC, steff456 commented
@navinkarkera now we have tests for the endpoints, as well I rebased this PR with the changes you made recently in your base branch. 

Please let me know what else is needed for this PR to be ready!

2023-12-12 05:20 UTC, steff456 commented
@navinkarkera I just updated this branch with the latest changes of the base branch. I had to do some modifications for the scroll to work with the drag and drop given that both were using `refs` and `useEffect` simultaneously, but everything is working as expected now. The CI failed because of coverage, which I suspect is because of the fork and base branch PR. 

Please let me know if there's anything else needed in this PR for merging!

2023-12-13 12:48 UTC, navinkarkera commented
@steff456 The scrolling was not working properly after deleting a section. Also it broke scrolling for subsections.

I pushed a fix such that the page will only scroll if the element is not visible and it will align based on the position of the element in the screen. Now it works for both sections and subsections.

I'll merge this now. Thanks for you work!

2023-12-13 12:50 UTC, steff456 commented
Thanks for all the review @navinkarkera! 🎉

2023-12-13 12:55 UTC, merged