[temp] feat: add import taxonomy button
open-craft/frontend-app-course-authoring pull request #8
Opened 2023-11-07 22:44 UTC by rpenido

2023-11-08 00:26 UTC, pomegranited requested changes
@rpenido Could you have a look at [ADR 002](https://github.com/openedx/frontend-template-application/blob/master/docs/decisions/0002-feature-based-application-organization.rst)? According to that, we should add a new `import-tags` folder for this feature, with the components and functions in separate files underneath.

2023-11-08 00:26 UTC, pomegranited commented on src/taxonomy/data/thunks.js
> +      taxonomyName = prompt('Enter a name for the new taxonomy');
Strings should be translatable.

2023-11-08 00:26 UTC, pomegranited commented on src/taxonomy/data/thunks.js
> +      taxonomyName = prompt('Enter a name for the new taxonomy');
And using `prompt` and `alert` is temporary -- please add a comment at the top of this function to this effect so upstream know why we're doing it this way for now.

2023-11-08 23:30 UTC, pomegranited approved these changes
👍 This looks and works great @rpenido !

I'm not sure if we need tests added though? It might be difficult to test this temporary `prompt`/`alert` flow.

- [x] I tested this on my devstack with this branch merged with https://github.com/openedx/frontend-app-course-authoring/pull/655 so I could see the imported tags.
- [x] I read through the code
- [x] I checked for accessibility issues by using my keyboard to navigate.
- [x] Includes documentation
- [x] All strings are translatable.

2023-11-09 12:40 UTC, rpenido commented
> I'm not sure if we need tests added though? It might be difficult to test this temporary prompt/alert flow.

I agree. We expect this code to be temporary. I will check if the coverage report would allow us to let it pass.

Closed in favor of:
- https://github.com/openedx/frontend-app-course-authoring/pull/675

2023-11-09 12:40 UTC, closed without merging